language: cpp

compiler:
  - gcc
  - clang

before_install:
  - chmod +x install-environment-linux.sh
  - ./install-environment-linux.sh apt

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - sudo ldconfig
  - ./ut_flappy_bear

# TODO: try make UT work on travis, SDL functions may not work correctly

