language: cpp

compiler:
  - gcc
  - clang

before_install:
  - chmod +x install-environment-ubuntu.sh
  - ./install-environment-ubuntu.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

# TODO: try make UT work on travis

