language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:antumdeluge/sdl2
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgl1-mesa-dev libsdl2-dev libsdl2-image-dev
  - sudo apt-get install -qq libboost-dev libboost-test-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

# TODO: try make UT work on travis

