language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo echo "deb http://ppa.launchpad.net/antumdeluge/sdl2/ubuntu precise main" >> /etc/apt/sources.list
  - sudo echo "deb-src http://ppa.launchpad.net/antumdeluge/sdl2/ubuntu precise main" >> /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

